CREATE TABLE alternativa( 
      id  integer generated by default as identity     NOT NULL , 
      questao_id integer    NOT NULL , 
      descricao blob sub_type 1    NOT NULL , 
      is_correta char(1)    DEFAULT false  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE alternativa_resposta_questao( 
      id  integer generated by default as identity     NOT NULL , 
      alternativa_id integer    NOT NULL , 
      questao_usuario_prova_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE grupo( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      descricao blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE grupo_prova( 
      id  integer generated by default as identity     NOT NULL , 
      prova_id integer    NOT NULL , 
      grupo_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE grupo_usuario( 
      id  integer generated by default as identity     NOT NULL , 
      usuario_id integer    NOT NULL , 
      grupo_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE prova( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      sucinto blob sub_type 1    NOT NULL , 
      minutos_realizacao integer   , 
      cor_primaria blob sub_type 1    NOT NULL , 
      cor_secundaria blob sub_type 1    NOT NULL , 
      usuario_responsavel integer    NOT NULL , 
      is_publica char(1)    DEFAULT false  NOT NULL , 
      inicio timestamp    DEFAULT now()  NOT NULL , 
      fim timestamp    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE questao( 
      id  integer generated by default as identity     NOT NULL , 
      pergunta blob sub_type 1    NOT NULL , 
      is_multipla_escolha char(1)    DEFAULT true  NOT NULL , 
      prova_id integer    NOT NULL , 
      minutos_realizacao integer   , 
      peso float  (10,3)    NOT NULL , 
      is_obrigatoria char(1)    DEFAULT true  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE questao_usuario_prova( 
      id  integer generated by default as identity     NOT NULL , 
      questao_id integer    NOT NULL , 
      usuario_prova_id integer    NOT NULL , 
      resposta_usuario blob sub_type 1   , 
      peso float  (10,3)    NOT NULL , 
      dt_registro timestamp    DEFAULT now()  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE resposta( 
      id  integer generated by default as identity     NOT NULL , 
      questao_id integer    NOT NULL , 
      resposta blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE usuario( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      email blob sub_type 1    NOT NULL , 
      senha blob sub_type 1    NOT NULL , 
      is_professor char(1)    DEFAULT false  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE usuario_prova( 
      id  integer generated by default as identity     NOT NULL , 
      usuario_id integer    NOT NULL , 
      prova_id integer    NOT NULL , 
      inicio timestamp    DEFAULT now()  NOT NULL , 
      fim timestamp   , 
 PRIMARY KEY (id)) ; 

 
  
 ALTER TABLE alternativa ADD CONSTRAINT fk_alternativa_1 FOREIGN KEY (questao_id) references questao(id); 
ALTER TABLE alternativa_resposta_questao ADD CONSTRAINT alternativa_resposta_questao_6048113797846 FOREIGN KEY (alternativa_id) references alternativa(id); 
ALTER TABLE alternativa_resposta_questao ADD CONSTRAINT alternativa_resposta_questao_604811379785b FOREIGN KEY (questao_usuario_prova_id) references questao_usuario_prova(id); 
ALTER TABLE grupo_prova ADD CONSTRAINT fk_grupo_prova_1 FOREIGN KEY (prova_id) references prova(id); 
ALTER TABLE grupo_prova ADD CONSTRAINT fk_grupo_prova_2 FOREIGN KEY (grupo_id) references grupo(id); 
ALTER TABLE grupo_usuario ADD CONSTRAINT fk_grupo_usuario_1 FOREIGN KEY (usuario_id) references usuario(id); 
ALTER TABLE grupo_usuario ADD CONSTRAINT fk_grupo_usuario_2 FOREIGN KEY (grupo_id) references grupo(id); 
ALTER TABLE prova ADD CONSTRAINT fk_prova_1 FOREIGN KEY (usuario_responsavel) references usuario(id); 
ALTER TABLE questao ADD CONSTRAINT fk_questao_1 FOREIGN KEY (prova_id) references prova(id); 
ALTER TABLE questao_usuario_prova ADD CONSTRAINT fk_questao_usuario_prova_1 FOREIGN KEY (questao_id) references questao(id); 
ALTER TABLE questao_usuario_prova ADD CONSTRAINT fk_questao_usuario_prova_2 FOREIGN KEY (usuario_prova_id) references usuario_prova(id); 
ALTER TABLE resposta ADD CONSTRAINT fk_resposta_1 FOREIGN KEY (questao_id) references questao(id); 
ALTER TABLE usuario_prova ADD CONSTRAINT fk_usuario_prova_1 FOREIGN KEY (usuario_id) references usuario(id); 
ALTER TABLE usuario_prova ADD CONSTRAINT fk_usuario_prova_2 FOREIGN KEY (prova_id) references prova(id); 

  
